# This is a basic workflow to help you get started with Actions

name: prod-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    types: [ assigned ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # 准备 pnpm环境
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.30.1
      # 配置rsa密钥自动登陆
      - uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup knownhosts
        run: ssh-keyscan ${{ secrets.REMOTE_ORIGIN }} >> ~/.ssh/known_hosts

      - name: Install dependence
        run: |
          echo 开始----安装依赖
          pnpm install
      - name: Build
        run: |
          echo 开始----构建
          npm run build
      - name: Compress dist
        run: |
          echo 开始----压缩
          npm run compress
      # 上传压缩的内容
      - name: Upload package
        run: |
          echo 开始---上传
          npm run upload
      # 部署上传的包
      - name: Deploy
        run: |
          echo 开始----部署
          npm run deploy